name: 'Generate Python SBOM'
description: 'A GitHub Action to generate SBOM using CycloneDX for Python projects and upload it to Dependency Track.'
author: 'Your Name or Organization'
inputs:
  python_version:
    description: 'Python version to setup'
    required: true
    default: '3.13'
  architecture:
    description: 'Architecture of the Python interpreter (x86, x64, arm64)'
    required: false
    default: 'x64'
  server_hostname:
    description: 'Dependency Track server hostname'
    required: true
  api_key:
    description: 'API key for Dependency Track'
    required: true
  project_name:
    description: 'Project name for Dependency Track'
    required: true
  project_version:
    description: 'Project version for Dependency Track'
    required: true
  bom_filename:
    description: 'Filename for the BOM'
    required: false
    default: './sbom.json'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CycloneDX BOM Tool
      run: |
        python3 -m pip install cyclonedx-bom
      shell: bash

    - name: Generate SBOM from requirements.txt
      run: |
        cyclonedx-py -r -i ./requirements.txt -o ${{ inputs.bom_filename }}
      shell: bash
      
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: bom-artifact
        path: sbom.json

    - name: Download SBOM artifact
      uses: actions/download-artifact@v4
      with:
        name: bom-artifact

    - name: List Directory Contents
      run: ls -la
      shell: bash
      
    - name: Upload BOM to Dependency Track
      uses: DependencyTrack/gh-upload-sbom@v3
      with:
        serverHostname: ${{ inputs.server_hostname }}
        apiKey: ${{ inputs.api_key }}
        projectName: ${{ inputs.project_name }}
        projectVersion: ${{ inputs.project_version }}
        bomFile: ${{ inputs.bom_filename }}
        autoCreate: true
